version: '3.8'

services:
  photo-app:
    build: .
    container_name: photo_collection_app
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}